# Site settings
title: Caden Burleson
email: hello@slamatron.com
description: "We are a games company. We want to bring the development process to you as we work to create great things. Come hangout and chat with us here : https://discord.gg/zz8FWU4"
baseurl: ""
url: "http://Slamatron.com"
twitter_username: Slamatron
# github_username: cadenburleson

# Build settings
markdown: kramdown
permalink: pretty
