# Site settings
title: Slamatron
email: caden.burleson@gmail.com
description: "We are a games company. We want to bring the development process to you as we work to create great things."
baseurl: ""
url: "http://Slamatron.com"
twitter_username: Slamatron
github_username: cadenburleson

# Build settings
markdown: kramdown
permalink: pretty
